[project]
name = "ibkr-based-trading-app"
version = "0.1.0"
description = ""
authors = [
    {name = "Alejandro4365",email = "alejandro917ramos@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas (>=3.0.3,<4.0.0)",
    "matplotlib (>=3.10.9,<4.0.0)",
    "pyqt6 (==6.7.0)",
    "pyqt6-qt6 (==6.7.0)",
    "ib-insync (>=0.9.86,<0.10.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
